OBJS = SumOfPrimes.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

SumOfPrimes : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o SumOfPrimes

SumOfPrimes.o : SumOfPrimes.cpp
			 $(CC) $(CFLAGS) SumOfPrimes.cpp
			 
clean:
	\rm *.o *~ SumOfPrimes